"""fase2 ordem producao rodada coleta medicao auditoria

Revision ID: 7786761cc626
Revises: d5de80549d4f
Create Date: 2026-08-26 21:50:41.651060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7786761cc626'
down_revision: Union[str, Sequence[str], None] = 'd5de80549d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('numero_ordem', sa.String(length=60), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peca_id', 'numero_ordem', name='uq_ordem_peca_numero')
    )
    op.create_table('rodadas_coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('amostras_calculadas', sa.Integer(), nullable=False),
    sa.Column('amostras_ajustadas', sa.Integer(), nullable=True),
    sa.Column('justificativa_ajuste', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'FINALIZADA', 'FINALIZADA_COM_PENDENCIA', name='status_rodada'), nullable=False),
    sa.Column('motivo_encerramento_antecipado', sa.Enum('ORDEM_INTERROMPIDA', 'ORDEM_CANCELADA', 'QUANTIDADE_MENOR_QUE_PREVISTO', 'NAO_CONFORMIDADE_PROCESSO', 'OUTRO', name='motivo_encerramento'), nullable=True),
    sa.Column('motivo_detalhe', sa.Text(), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_producao.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordem_id', 'etapa_id', name='uq_rodada_ordem_etapa')
    )
    op.create_table('medicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('caracteristica_id', sa.Integer(), nullable=False),
    sa.Column('amostra_numero', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('operador_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['caracteristicas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas_coleta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rodada_id', 'caracteristica_id', 'amostra_numero', name='uq_medicao_amostra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicoes')
    op.drop_table('rodadas_coleta')
    op.drop_table('ordens_producao')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
