"""fase4_nao_conformidade_plano_acao

Revision ID: c15443a25a2f
Revises: 7786761cc626
Create Date: 2026-08-27 10:41:26.241634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15443a25a2f'
down_revision: Union[str, Sequence[str], None] = '7786761cc626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nao_conformidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_rnc', sa.String(length=30), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=True),
    sa.Column('etapa_id', sa.Integer(), nullable=True),
    sa.Column('caracteristica_id', sa.Integer(), nullable=True),
    sa.Column('rodada_id', sa.Integer(), nullable=True),
    sa.Column('descricao_problema', sa.Text(), nullable=False),
    sa.Column('quantidade_afetada', sa.Integer(), nullable=False),
    sa.Column('classificacao', sa.Enum('CRITICA', 'MAIOR', 'MENOR', name='classificacao_nc'), nullable=False),
    sa.Column('origem', sa.Enum('PROCESSO', 'MATERIA_PRIMA', 'PROJETO', 'INSTRUMENTO', 'MAO_DE_OBRA', 'OUTRO', name='origem_nc'), nullable=False),
    sa.Column('causa_raiz_preliminar', sa.Text(), nullable=True),
    sa.Column('disposicao', sa.Enum('RETRABALHO', 'SUCATA', 'USO_COMO_ESTA', 'DEVOLUCAO_FORNECEDOR', 'RECLASSIFICACAO', name='disposicao_nc'), nullable=True),
    sa.Column('responsavel_analise_id', sa.Integer(), nullable=True),
    sa.Column('necessita_plano_acao', sa.Boolean(), nullable=False),
    sa.Column('aberto_por_id', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_encerramento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANALISE', 'EM_TRATAMENTO', 'ENCERRADA', name='status_nc'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aberto_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['caracteristicas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_producao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsavel_analise_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas_coleta.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nao_conformidades_numero_rnc'), 'nao_conformidades', ['numero_rnc'], unique=True)
    op.create_table('planos_acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_id', sa.Integer(), nullable=False),
    sa.Column('metodologia_causa_raiz', sa.Enum('ISHIKAWA', 'CINCO_PORQUES', 'LIVRE', name='metodologia_causa_raiz'), nullable=False),
    sa.Column('conclusao_causa_raiz', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'AGUARDANDO_VERIFICACAO', 'ENCERRADO', 'REABERTO', name='status_plano_acao'), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nc_id'], ['nao_conformidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acoes_corretivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('data_execucao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CONCLUIDA', name='status_acao_corretiva'), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_acao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causas_5porques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('marcada_como_raiz', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_acao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plano_id', 'nivel', name='uq_5porques_plano_nivel')
    )
    op.create_table('causas_ishikawa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('METODO', 'MAO_DE_OBRA', 'MAQUINA', 'MATERIAL', 'MEIO_AMBIENTE', 'MEDICAO', name='categoria_ishikawa'), nullable=False),
    sa.Column('descricao_causa', sa.Text(), nullable=False),
    sa.Column('marcada_como_raiz', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_acao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verificacoes_eficacia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.Column('data_verificacao', sa.Date(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.Enum('EFICAZ', 'NAO_EFICAZ', name='resultado_verificacao'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_acao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacoes_eficacia')
    op.drop_table('causas_ishikawa')
    op.drop_table('causas_5porques')
    op.drop_table('acoes_corretivas')
    op.drop_table('planos_acao')
    op.drop_index(op.f('ix_nao_conformidades_numero_rnc'), table_name='nao_conformidades')
    op.drop_table('nao_conformidades')
    # ### end Alembic commands ###
