"""fase1 usuarios peca etapa caracteristica

Revision ID: d5de80549d4f
Revises: 
Create Date: 2026-08-26 20:28:50.364942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5de80549d4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('cliente', sa.String(length=120), nullable=True),
    sa.Column('desenho', sa.String(length=120), nullable=True),
    sa.Column('revisao', sa.String(length=30), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_peca'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pecas_codigo'), 'pecas', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('OPERADOR', 'ANALISTA_QUALIDADE', 'GESTOR_QUALIDADE', name='perfil_usuario'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_usuario'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    op.create_table('etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('numero_etapa', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('freq_numerador', sa.Integer(), nullable=False),
    sa.Column('freq_denominador', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_etapa'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peca_id', 'numero_etapa', name='uq_etapa_peca_numero')
    )
    op.create_table('caracteristicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('posicao_desenho', sa.String(length=30), nullable=True),
    sa.Column('nominal', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('tol_superior', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('tol_inferior', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('unidade', sa.Enum('MM', 'CM', 'POLEGADA', name='unidade_medida'), nullable=False),
    sa.Column('instrumento', sa.Enum('PAQUIMETRO', 'MICROMETRO', 'RELOGIO_COMPARADOR', 'OUTRO', name='instrumento_medicao'), nullable=True),
    sa.Column('casas_decimais', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_caracteristica'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caracteristicas')
    op.drop_table('etapas')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pecas_codigo'), table_name='pecas')
    op.drop_table('pecas')
    # ### end Alembic commands ###
